### ISSUE TITLE
您好，请问AMD Ryzen 2600x可以用这套教程装黑苹果吗？

### ISSUE THREAD

**Issue by scriptwang** [MrNegativeTW/Ryzen-Hackintosh-Tutorial#1]
配置如下:
CPU:AMD Ryzen 2600x
主板:华硕B350 PLUS
显卡:GTX 1050ti

请您评估一下以上硬件能装黑苹果吗?
十分感谢，期待您的回复:)

**Comment by MrNegativeTW** [comment]
估計是可以的，不過主機板與教學不同，所以驅動方面需要在多多爬文

**Comment by scriptwang** [comment]
@MrNegativeTW  
好的，谢谢:)

**Comment by scriptwang** [comment]
试了下High serria 10.13.3 
安装能顺利完成 usb声音都有
就是显卡驱动装不上 
一装就黑屏
Google爬了很多文都没有解决这个问题：（

**Comment by MrNegativeTW** [comment]
除了確認版本號之外，還有SMBIOS要設定，教學裡忘記提到這一點了
這個文章看看吧
https://www.tonymacx86.com/threads/fix-10-12-10-13-nvidia-2-3-4-5-6-7-9-10xx-series-black-screen.203430/

**Comment by scriptwang** [comment]
@MrNegativeTW  最后我发现其实问题只是DVI线接触不良，重新插拔一下就好了，不过还是十分感谢你制作的git-book哦:)
