### ISSUE TITLE
postinstall 問題

### ISSUE THREAD

**Issue by brook0903** [MrNegativeTW/Ryzen-Hackintosh-Tutorial#2]
輸入 sh /Volumes/SierraAMD/PostInstall/post.sh 之後出現no such file or directory

**Comment by MrNegativeTW** [comment]
我想到的幾個方法：
1. 請先確認是否使用隨身碟開機
2. 輸入每個資料夾的第一字之後，按 `Tab` 可以自動完成，避免輸入錯誤
3. 用 `ls`  指令確認目錄下的所有檔案，若無 `post.sh` ，那就是下載到的安裝檔沒包含

**Comment by brook0903** [comment]
忘記提調每次安裝條跑到結尾完成後就會顯示安裝失敗 要我重新啟動或是關機

**Comment by brook0903** [comment]
能問一下安裝檔應該要載哪款的嗎?? 
那個網站上有很多款不太了解能用哪種的
cpu: a8-5600k

**Comment by MrNegativeTW** [comment]
安裝條是指 macOS 的還是 post.sh 的？

剛剛看網站，新提供的安裝檔裡面似乎沒附 post.sh 這檔案，需要找舊版的，我自己下載到的檔名是 SierraAMD_V5.dmg，可以找找網路上有沒有這版可以抓

**Comment by brook0903** [comment]
安裝條是macos的 
還是您能提供SierraAMD_V5.dmg嗎??

**Comment by MrNegativeTW** [comment]
[這是當時 AMD OS X 提供的連結](https://drive.google.com/file/d/0B7XXHpOg2peBSTBFeUc3dkJUTUU/view?usp=sharing)

下載解壓後使用 Transmac 製作隨身碟就可以了

**Comment by brook0903** [comment]
好的 謝謝您 我來試試看
如果想要雙系統是否該把已有系統的硬碟先拔除??

**Comment by MrNegativeTW** [comment]
我個人是拔到剩下要安裝 Windows 的硬碟，推薦這樣搞，不然 Windows 安裝的時候會對 macOS 產生不良的影響

**Comment by brook0903** [comment]
先安裝win再裝macos跟先裝macos再裝win有差嗎??

**Comment by MrNegativeTW** [comment]
其實應該是沒差，不過當時我為了測試，是直接把 macOS 裝在 Windows 的硬碟上，確認可以用之後才去買硬碟正式安裝 macOS，然後再把被我砍掉的 Windows 裝回來

**Comment by brook0903** [comment]
好的 謝謝您
