### ISSUE TITLE
蘋果官網的dmg是否可以製作成開機碟?

### ISSUE THREAD

**Issue by samhuang1111** [MrNegativeTW/Ryzen-Hackintosh-Tutorial#3]
如題
蘋果官網的dmg是否可以製作成開機碟?
還是必須要找已經被破解好的dmg?

**Comment by MrNegativeTW** [comment]
我沒試過，不過據我所知是可以的
但以我這版(10.12.6)為例，安裝完成後有 Post-Install 的步驟要做，是因為DMG製作者已經把那些內核檔案整合進DMG了，若是原始DMG的話，就要自己找地方替換。

**Comment by chanwang5** [comment]
> 如題
> 蘋果官網的dmg是否可以製作成開機碟?
> 還是必須要找已經被破解好的dmg?

可以。https://diskmakerx.com
